// splashPack.js — the splash screens shipped with a deployment.
//
// The build embeds map/splashpack.json into game-play.js, the same way
// bundledWorld.js embeds the world. The pack is generated by
// tools/pack_splash.mjs from map/splash.json + the referenced worlds in
// map/worlds/, so a deployed game can show its authored menu shots without a
// server. Entries: [{ world: <library path>, cam: <splash cam id>,
// bundle: <inline WorldBundle data> }].

import splashPack from '../../map/splashpack.json';

/** @type {{entries: Array<{world:string,cam:string,bundle:object}>}|null} */
export const BUNDLED_SPLASH = splashPack;
